# Generated by Django 5.2.6 on 2025-09-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
